name: GitHub Actions

on:
  push:
    branches: ["*"]

jobs:
  build01:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm ci
      - run: npm run test
      - run: npm run build
      - run: npm run deploy

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Runa a one-line script
        run: echo Build!
        
  deploy-developer:
    runs-on: ubuntu-latest
    environment:
      name: developer
      url: 'teste01.com'
    needs: build  
    steps:
      - name: Runa a one-line script
        run: echo Deploy Developer! 
        
  deploy-homologation:
    runs-on: ubuntu-latest
    environment:
      name: homologation
      url: 'teste02.com'
    needs: deploy-developer
    steps:
      - name: Runa a one-line script
        run: echo Deploy Homologation!
        
  deploy-production:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: 'teste03.com'
    needs: deploy-homologation
    steps:
      - name: Runa a one-line script
        run: echo Deploy Production!             
